<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class MasterObatSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('master_obats')->insert([
            [
                'kode_obat' => 'OBT0001',
                'nama_obat' => 'Paracetamol 500mg',
                'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Paracetamol 500mg',
                'indikasi' => 'Menurunkan demam dan meredakan nyeri',
                'dosis' => '3x sehari 1 tablet setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 30,
                'harga_beli' => 450.00,
                'harga_jual' => 800.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(2),
                'no_batch' => 'BATCH2025A',
                'is_generik' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0002',
                'nama_obat' => 'Amoxicillin 500mg',
                'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Amoxicillin trihydrate 500mg',
                'indikasi' => 'Infeksi bakteri ringan hingga sedang',
                'dosis' => '3x sehari 1 kapsul sebelum makan',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 20,
                'harga_beli' => 600.00,
                'harga_jual' => 1000.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(1)->addMonths(6),
                'no_batch' => 'BATCH2025B',
                'is_generik' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0003',
                'nama_obat' => 'Ibuprofen 200mg',
                 'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Ibuprofen 200mg',
                'indikasi' => 'Nyeri, demam, peradangan',
                'dosis' => '3x sehari 1 tablet setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 700.00,
                'harga_jual' => 1100.00,
                'tgl_kadaluarsa' => Carbon::now()->addYear(),
                'no_batch' => 'BATCH2025C',
                'is_generik' => false,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0004',
                'nama_obat' => 'Cetirizine 10mg',
                 'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Cetirizine HCl 10mg',
                'indikasi' => 'Alergi, rhinitis, urtikaria',
                'dosis' => '1x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 40,
                'harga_beli' => 400.00,
                'harga_jual' => 750.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(3),
                'no_batch' => 'BATCH2026D',
                'is_generik' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0005',
                'nama_obat' => 'Loperamide 2mg',
                 'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Loperamide HCl 2mg',
                'indikasi' => 'Diare akut dan kronis',
                'dosis' => '2 kapsul awal, lalu 1 setiap buang air besar',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 15,
                'harga_beli' => 500.00,
                'harga_jual' => 850.00,
                'tgl_kadaluarsa' => Carbon::now()->addYear(),
                'no_batch' => 'BATCH2025E',
                'is_generik' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0006',
                'nama_obat' => 'Omeprazole 20mg',
                'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Omeprazole 20mg',
                'indikasi' => 'Asam lambung, tukak lambung',
                'dosis' => '1 kapsul sebelum makan pagi',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 20,
                'harga_beli' => 800.00,
                'harga_jual' => 1300.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(2),
                'no_batch' => 'BATCH2026F',
                'is_generik' => false,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0007',
                'nama_obat' => 'Simvastatin 10mg',
                 'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Simvastatin 10mg',
                'indikasi' => 'Menurunkan kolesterol',
                'dosis' => '1x sehari malam hari',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 650.00,
                'harga_jual' => 1000.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(2),
                'no_batch' => 'BATCH2026G',
                'is_generik' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0008',
                'nama_obat' => 'Amlodipine 5mg',
                 'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Amlodipine besylate 5mg',
                'indikasi' => 'Hipertensi, angina',
                'dosis' => '1 tablet sehari',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 30,
                'harga_beli' => 550.00,
                'harga_jual' => 900.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(2),
                'no_batch' => 'BATCH2026H',
                'is_generik' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0009',
                'nama_obat' => 'Metformin 500mg',
                 'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Metformin HCl 500mg',
                'indikasi' => 'Diabetes mellitus tipe 2',
                'dosis' => '2x sehari setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 500.00,
                'harga_jual' => 850.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(1),
                'no_batch' => 'BATCH2025I',
                'is_generik' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'kode_obat' => 'OBT0010',
                'nama_obat' => 'Cefixime 100mg',
                'kategori_id' => 1,
                'sub_kategori_id' => 2,
                'golongan_id' => 3,
                'satuan_id' => 7,
                'sediaan_id' => 1,
                'pabrikan_id' => 1,
                'distributor_id' => 1,
                'rak_id' => 1,
                'komposisi' => 'Cefixime trihydrate 100mg',
                'indikasi' => 'Infeksi saluran kemih dan pernapasan',
                'dosis' => '2x sehari 1 kapsul',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 15,
                'harga_beli' => 1000.00,
                'harga_jual' => 1600.00,
                'tgl_kadaluarsa' => Carbon::now()->addYears(1),
                'no_batch' => 'BATCH2025J',
                'is_generik' => false,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
