<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MasterObatSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $columns = array_flip(Schema::getColumnListing('master_obats'));

        $categories = DB::table('categories')->pluck('id', 'code')->all();
        $golongans = DB::table('golongan_obats')->pluck('id', 'kode')->all();
        $mainGolongans = DB::table('main_golongan_obats')->pluck('id', 'kode')->all();
        $subGolongans = DB::table('sub_golongan_obats')->pluck('id', 'kode')->all();
        $satuans = DB::table('satuans')->pluck('id', 'kode')->all();
        $sediaans = DB::table('sediaan_obats')->pluck('id', 'kode')->all();
        $pabrikans = DB::table('pabrikan')->orderBy('id')->pluck('id')->values()->all();
        $distributors = DB::table('distributors')->orderBy('id')->pluck('id')->values()->all();
        $raks = DB::table('rak_penyimpanans')->orderBy('id')->pluck('id')->values()->all();

        $fallback = [
            'category_id' => DB::table('categories')->value('id'),
            'golongan_id' => DB::table('golongan_obats')->value('id'),
            'satuan_id' => DB::table('satuans')->value('id'),
            'sediaan_id' => DB::table('sediaan_obats')->value('id'),
        ];

        $rows = collect($this->catalog())->map(function (array $item, int $index) use (
            $now,
            $columns,
            $categories,
            $golongans,
            $mainGolongans,
            $subGolongans,
            $satuans,
            $sediaans,
            $pabrikans,
            $distributors,
            $raks,
            $fallback
        ) {
            $golonganId = $golongans[$item['golongan']] ?? $fallback['golongan_id'];
            $mainCode = $item['main'] ?? $this->defaultMainGolongan($item['golongan'], $item['is_generik']);

            $row = [
                'kode_obat' => sprintf('OBT%04d', $index + 1),
                'nama_obat' => $item['nama'],
                'category_id' => $categories[$item['kategori']] ?? $fallback['category_id'],
                'golongan_id' => $golonganId,
                'main_golongan_id' => $mainCode ? ($mainGolongans[$mainCode] ?? null) : null,
                'sub_golongan_id' => isset($item['sub']) ? ($subGolongans[$item['sub']] ?? null) : null,
                'satuan_id' => $satuans[$item['satuan']] ?? $fallback['satuan_id'],
                'sediaan_id' => $sediaans[$item['sediaan']] ?? $fallback['sediaan_id'],
                'pabrikan_id' => $this->cycle($pabrikans, $index),
                'distributor_id' => $this->cycle($distributors, $index),
                'rak_id' => $this->cycle($raks, $index),
                'komposisi' => $item['komposisi'],
                'indikasi' => $item['indikasi'],
                'dosis' => $item['dosis'],
                'kemasan' => $item['kemasan'],
                'stok_minimum' => $item['stok_minimum'],
                'harga_beli' => $item['harga_beli'],
                'tgl_kadaluarsa' => $now->copy()->addMonths(24 + ($index % 24))->toDateString(),
                'no_batch' => sprintf('SEED%04d-%s', $index + 1, $now->format('ym')),
                'is_generik' => $item['is_generik'],
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ];

            return array_intersect_key($row, $columns);
        })->all();

        if ($rows === []) {
            return;
        }

        $updateColumns = array_values(array_diff(array_keys($rows[0]), ['kode_obat', 'created_at']));

        DB::table('master_obats')->upsert($rows, ['kode_obat'], $updateColumns);
    }

    private function defaultMainGolongan(string $golonganCode, bool $isGenerik): ?string
    {
        if ($golonganCode === 'OBK') {
            return $isGenerik ? 'OKG' : 'OKP';
        }

        if ($golonganCode === 'OTC') {
            return $isGenerik ? 'OTG' : 'OTP';
        }

        return null;
    }

    private function cycle(array $ids, int $index): ?int
    {
        if ($ids === []) {
            return null;
        }

        return $ids[$index % count($ids)];
    }

    private function catalog(): array
    {
        return [
            [
                'nama' => 'Paracetamol 500mg',
                'kategori' => 'ANL',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Paracetamol 500mg',
                'indikasi' => 'Demam dan nyeri ringan sampai sedang',
                'dosis' => '3-4x sehari 1 tablet setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 30,
                'harga_beli' => 450,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ibuprofen 200mg',
                'kategori' => 'ANL',
                'golongan' => 'OTC',
                'main' => 'OBST',
                'sub' => 'OT',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Ibuprofen 200mg',
                'indikasi' => 'Nyeri, demam, dan peradangan ringan',
                'dosis' => '3x sehari 1 tablet setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 700,
                'is_generik' => false,
            ],
            [
                'nama' => 'Asam Mefenamat 500mg',
                'kategori' => 'ANL',
                'golongan' => 'OBK',
                'satuan' => 'KPL',
                'sediaan' => 'SED-012',
                'komposisi' => 'Mefenamic acid 500mg',
                'indikasi' => 'Nyeri gigi, nyeri haid, dan nyeri otot',
                'dosis' => '3x sehari 1 kaplet setelah makan',
                'kemasan' => 'Strip isi 10 kaplet',
                'stok_minimum' => 25,
                'harga_beli' => 850,
                'is_generik' => true,
            ],
            [
                'nama' => 'Metamizole Sodium 500mg',
                'kategori' => 'ANL',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Metamizole sodium 500mg',
                'indikasi' => 'Nyeri sedang sampai berat dan demam',
                'dosis' => '3x sehari 1 tablet sesudah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 780,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ketorolac 10mg',
                'kategori' => 'ANL',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Ketorolac tromethamine 10mg',
                'indikasi' => 'Nyeri akut sedang sampai berat',
                'dosis' => '2-3x sehari 1 tablet setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 12,
                'harga_beli' => 1250,
                'is_generik' => true,
            ],
            [
                'nama' => 'Amoxicillin 500mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Amoxicillin trihydrate 500mg',
                'indikasi' => 'Infeksi bakteri ringan sampai sedang',
                'dosis' => '3x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 25,
                'harga_beli' => 650,
                'is_generik' => true,
            ],
            [
                'nama' => 'Cefadroxil 500mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Cefadroxil monohydrate 500mg',
                'indikasi' => 'Infeksi saluran napas, kulit, dan saluran kemih',
                'dosis' => '2x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 18,
                'harga_beli' => 1200,
                'is_generik' => true,
            ],
            [
                'nama' => 'Cefixime 100mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Cefixime trihydrate 100mg',
                'indikasi' => 'Infeksi saluran kemih dan pernapasan',
                'dosis' => '2x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 18,
                'harga_beli' => 1000,
                'is_generik' => true,
            ],
            [
                'nama' => 'Azithromycin 500mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Azithromycin dihydrate 500mg',
                'indikasi' => 'Infeksi bakteri saluran napas dan kulit',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 6 tablet',
                'stok_minimum' => 15,
                'harga_beli' => 3500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Ciprofloxacin 500mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'KPL',
                'sediaan' => 'SED-012',
                'komposisi' => 'Ciprofloxacin HCl 500mg',
                'indikasi' => 'Infeksi bakteri saluran kemih dan cerna',
                'dosis' => '2x sehari 1 kaplet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kaplet',
                'stok_minimum' => 20,
                'harga_beli' => 900,
                'is_generik' => true,
            ],
            [
                'nama' => 'Levofloxacin 500mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Levofloxacin hemihydrate 500mg',
                'indikasi' => 'Infeksi bakteri saluran napas dan saluran kemih',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 12,
                'harga_beli' => 1800,
                'is_generik' => true,
            ],
            [
                'nama' => 'Doxycycline 100mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Doxycycline hyclate 100mg',
                'indikasi' => 'Infeksi bakteri tertentu sesuai indikasi dokter',
                'dosis' => '1-2x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 12,
                'harga_beli' => 950,
                'is_generik' => true,
            ],
            [
                'nama' => 'Clindamycin 300mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Clindamycin HCl 300mg',
                'indikasi' => 'Infeksi bakteri anaerob dan infeksi kulit',
                'dosis' => '3x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 12,
                'harga_beli' => 1700,
                'is_generik' => true,
            ],
            [
                'nama' => 'Metronidazole 500mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Metronidazole 500mg',
                'indikasi' => 'Infeksi bakteri anaerob dan protozoa',
                'dosis' => '3x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 550,
                'is_generik' => true,
            ],
            [
                'nama' => 'Co-Amoxiclav 625mg',
                'kategori' => 'ABT',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'KPL',
                'sediaan' => 'SED-012',
                'komposisi' => 'Amoxicillin 500mg + clavulanic acid 125mg',
                'indikasi' => 'Infeksi bakteri yang memerlukan kombinasi beta-laktamase inhibitor',
                'dosis' => '3x sehari 1 kaplet sesuai resep dokter',
                'kemasan' => 'Strip isi 6 kaplet',
                'stok_minimum' => 10,
                'harga_beli' => 5200,
                'is_generik' => false,
            ],
            [
                'nama' => 'Pseudoephedrine Triprolidine Tablet',
                'kategori' => 'AFL',
                'golongan' => 'OTC',
                'main' => 'OBST',
                'sub' => 'PR',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Pseudoephedrine HCl 60mg + triprolidine HCl 2.5mg',
                'indikasi' => 'Gejala flu, hidung tersumbat, dan alergi',
                'dosis' => '3x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 15,
                'harga_beli' => 1250,
                'is_generik' => false,
            ],
            [
                'nama' => 'Chlorpheniramine Maleate 4mg',
                'kategori' => 'ALG',
                'golongan' => 'OTC',
                'main' => 'OBST',
                'sub' => 'OT',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Chlorpheniramine maleate 4mg',
                'indikasi' => 'Alergi, gatal, dan rhinitis alergi',
                'dosis' => '3x sehari 1 tablet',
                'kemasan' => 'Strip isi 12 tablet',
                'stok_minimum' => 30,
                'harga_beli' => 250,
                'is_generik' => true,
            ],
            [
                'nama' => 'Cetirizine 10mg',
                'kategori' => 'ALG',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Cetirizine HCl 10mg',
                'indikasi' => 'Rhinitis alergi dan urtikaria',
                'dosis' => '1x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 30,
                'harga_beli' => 400,
                'is_generik' => true,
            ],
            [
                'nama' => 'Loratadine 10mg',
                'kategori' => 'ALG',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Loratadine 10mg',
                'indikasi' => 'Alergi dan rhinitis alergi',
                'dosis' => '1x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 550,
                'is_generik' => false,
            ],
            [
                'nama' => 'Fexofenadine 120mg',
                'kategori' => 'ALG',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Fexofenadine HCl 120mg',
                'indikasi' => 'Rhinitis alergi dan urtikaria kronis',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 12,
                'harga_beli' => 2200,
                'is_generik' => false,
            ],
            [
                'nama' => 'Dextromethorphan 15mg',
                'kategori' => 'ABT-BTK',
                'golongan' => 'OTC',
                'main' => 'OBST',
                'sub' => 'OT',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Dextromethorphan HBr 15mg',
                'indikasi' => 'Batuk kering tidak berdahak',
                'dosis' => '3x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 450,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ambroxol 30mg',
                'kategori' => 'ABT-BTK',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Ambroxol HCl 30mg',
                'indikasi' => 'Batuk berdahak dan mukolitik',
                'dosis' => '3x sehari 1 tablet setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 480,
                'is_generik' => true,
            ],
            [
                'nama' => 'Guaifenesin Syrup 100mg/5mL',
                'kategori' => 'ABT-BTK',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-022',
                'komposisi' => 'Guaifenesin 100mg per 5mL',
                'indikasi' => 'Ekspektoran untuk membantu mengeluarkan dahak',
                'dosis' => '3x sehari 1 sendok takar',
                'kemasan' => 'Botol 60mL',
                'stok_minimum' => 12,
                'harga_beli' => 8500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Salbutamol 2mg',
                'kategori' => 'ASMA',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Salbutamol sulfate 2mg',
                'indikasi' => 'Bronkospasme pada asma dan PPOK',
                'dosis' => '3x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 350,
                'is_generik' => true,
            ],
            [
                'nama' => 'Salbutamol Inhaler 100mcg',
                'kategori' => 'ASMA',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'INH',
                'sediaan' => 'SED-035',
                'komposisi' => 'Salbutamol 100mcg per puff',
                'indikasi' => 'Serangan asma dan bronkospasme',
                'dosis' => '1-2 puff bila perlu sesuai anjuran dokter',
                'kemasan' => 'Inhaler 200 dosis',
                'stok_minimum' => 8,
                'harga_beli' => 42000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Budesonide Nebulizer 0.5mg/2mL',
                'kategori' => 'ASMA',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'VIAL',
                'sediaan' => 'SED-037',
                'komposisi' => 'Budesonide 0.5mg per 2mL',
                'indikasi' => 'Terapi pemeliharaan asma dengan nebulizer',
                'dosis' => 'Sesuai resep dokter',
                'kemasan' => 'Box isi 5 respule',
                'stok_minimum' => 8,
                'harga_beli' => 14500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Aminophylline 200mg',
                'kategori' => 'ASMA',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Aminophylline 200mg',
                'indikasi' => 'Bronkodilator pada asma dan PPOK',
                'dosis' => '2-3x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 12,
                'harga_beli' => 420,
                'is_generik' => true,
            ],
            [
                'nama' => 'Omeprazole 20mg',
                'kategori' => 'MGH',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Omeprazole 20mg',
                'indikasi' => 'GERD, gastritis, dan tukak lambung',
                'dosis' => '1x sehari 1 kapsul sebelum makan',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 25,
                'harga_beli' => 800,
                'is_generik' => true,
            ],
            [
                'nama' => 'Lansoprazole 30mg',
                'kategori' => 'MGH',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Lansoprazole 30mg',
                'indikasi' => 'Asam lambung dan tukak lambung',
                'dosis' => '1x sehari 1 kapsul sebelum makan',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 20,
                'harga_beli' => 950,
                'is_generik' => true,
            ],
            [
                'nama' => 'Antasida DOEN Suspensi',
                'kategori' => 'MGH',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'BTL',
                'sediaan' => 'SED-024',
                'komposisi' => 'Aluminium hydroxide + magnesium hydroxide',
                'indikasi' => 'Gejala maag, nyeri ulu hati, dan kembung',
                'dosis' => '3-4x sehari 1-2 sendok takar',
                'kemasan' => 'Botol 60mL',
                'stok_minimum' => 15,
                'harga_beli' => 6200,
                'is_generik' => true,
            ],
            [
                'nama' => 'Sucralfate Suspensi 500mg/5mL',
                'kategori' => 'MGH',
                'golongan' => 'OBK',
                'satuan' => 'BTL',
                'sediaan' => 'SED-024',
                'komposisi' => 'Sucralfate 500mg per 5mL',
                'indikasi' => 'Tukak lambung dan iritasi saluran cerna atas',
                'dosis' => '4x sehari 2 sendok takar sesuai resep dokter',
                'kemasan' => 'Botol 100mL',
                'stok_minimum' => 10,
                'harga_beli' => 18500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Domperidone 10mg',
                'kategori' => 'PNG',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Domperidone 10mg',
                'indikasi' => 'Mual, muntah, dan gangguan motilitas lambung',
                'dosis' => '3x sehari 1 tablet sebelum makan sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 15,
                'harga_beli' => 500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ondansetron 4mg',
                'kategori' => 'PNG',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Ondansetron 4mg',
                'indikasi' => 'Mual dan muntah',
                'dosis' => '2-3x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 12,
                'harga_beli' => 1300,
                'is_generik' => true,
            ],
            [
                'nama' => 'Loperamide 2mg',
                'kategori' => 'DRE',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Loperamide HCl 2mg',
                'indikasi' => 'Diare akut non spesifik',
                'dosis' => '2 kapsul awal, lalu 1 kapsul setelah BAB cair',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 20,
                'harga_beli' => 500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Oralit Sachet',
                'kategori' => 'DRE',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'SACH',
                'sediaan' => 'SED-020',
                'komposisi' => 'Oral rehydration salts',
                'indikasi' => 'Membantu mengganti cairan dan elektrolit saat diare',
                'dosis' => 'Larutkan 1 sachet sesuai petunjuk kemasan',
                'kemasan' => 'Sachet serbuk oral',
                'stok_minimum' => 40,
                'harga_beli' => 850,
                'is_generik' => true,
            ],
            [
                'nama' => 'Bisacodyl 5mg',
                'kategori' => 'KST',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'TBL',
                'sediaan' => 'SED-005',
                'komposisi' => 'Bisacodyl 5mg',
                'indikasi' => 'Konstipasi atau sembelit',
                'dosis' => '1-2 tablet malam hari bila perlu',
                'kemasan' => 'Strip isi 10 tablet salut enterik',
                'stok_minimum' => 15,
                'harga_beli' => 550,
                'is_generik' => false,
            ],
            [
                'nama' => 'Lactulose Syrup 3.335g/5mL',
                'kategori' => 'KST',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-022',
                'komposisi' => 'Lactulose 3.335g per 5mL',
                'indikasi' => 'Konstipasi dan pelunak feses',
                'dosis' => '1-2 sendok takar per hari sesuai kebutuhan',
                'kemasan' => 'Botol 60mL',
                'stok_minimum' => 10,
                'harga_beli' => 28000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Amlodipine 5mg',
                'kategori' => 'HTN',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Amlodipine besylate 5mg',
                'indikasi' => 'Hipertensi dan angina',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 30,
                'harga_beli' => 550,
                'is_generik' => true,
            ],
            [
                'nama' => 'Candesartan 8mg',
                'kategori' => 'HTN',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Candesartan cilexetil 8mg',
                'indikasi' => 'Hipertensi dan gagal jantung',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 18,
                'harga_beli' => 1200,
                'is_generik' => true,
            ],
            [
                'nama' => 'Valsartan 80mg',
                'kategori' => 'HTN',
                'golongan' => 'OBK',
                'satuan' => 'KPL',
                'sediaan' => 'SED-012',
                'komposisi' => 'Valsartan 80mg',
                'indikasi' => 'Hipertensi dan terapi kardiovaskular',
                'dosis' => '1x sehari 1 kaplet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kaplet',
                'stok_minimum' => 15,
                'harga_beli' => 1550,
                'is_generik' => true,
            ],
            [
                'nama' => 'Captopril 25mg',
                'kategori' => 'HTN',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Captopril 25mg',
                'indikasi' => 'Hipertensi dan gagal jantung',
                'dosis' => '2-3x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 250,
                'is_generik' => true,
            ],
            [
                'nama' => 'Furosemide 40mg',
                'kategori' => 'JTG',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Furosemide 40mg',
                'indikasi' => 'Edema dan hipertensi tertentu',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 300,
                'is_generik' => true,
            ],
            [
                'nama' => 'Bisoprolol 5mg',
                'kategori' => 'JTG',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Bisoprolol fumarate 5mg',
                'indikasi' => 'Hipertensi, angina, dan gagal jantung',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 15,
                'harga_beli' => 900,
                'is_generik' => true,
            ],
            [
                'nama' => 'Isosorbide Dinitrate 5mg',
                'kategori' => 'JTG',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-009',
                'komposisi' => 'Isosorbide dinitrate 5mg',
                'indikasi' => 'Angina pektoris',
                'dosis' => 'Diletakkan di bawah lidah sesuai resep dokter',
                'kemasan' => 'Botol isi 100 tablet sublingual',
                'stok_minimum' => 8,
                'harga_beli' => 380,
                'is_generik' => true,
            ],
            [
                'nama' => 'Simvastatin 20mg',
                'kategori' => 'KOL',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Simvastatin 20mg',
                'indikasi' => 'Menurunkan kolesterol',
                'dosis' => '1x sehari malam hari sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 700,
                'is_generik' => true,
            ],
            [
                'nama' => 'Atorvastatin 20mg',
                'kategori' => 'KOL',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Atorvastatin calcium 20mg',
                'indikasi' => 'Menurunkan kolesterol dan trigliserida',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 18,
                'harga_beli' => 1600,
                'is_generik' => true,
            ],
            [
                'nama' => 'Metformin 500mg',
                'kategori' => 'DM',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Metformin HCl 500mg',
                'indikasi' => 'Diabetes mellitus tipe 2',
                'dosis' => '2-3x sehari setelah makan sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Glimepiride 2mg',
                'kategori' => 'DM',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Glimepiride 2mg',
                'indikasi' => 'Diabetes mellitus tipe 2',
                'dosis' => '1x sehari sebelum makan sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 18,
                'harga_beli' => 650,
                'is_generik' => true,
            ],
            [
                'nama' => 'Gliclazide MR 30mg',
                'kategori' => 'DM',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'TBL',
                'sediaan' => 'SED-011',
                'komposisi' => 'Gliclazide modified release 30mg',
                'indikasi' => 'Diabetes mellitus tipe 2',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet lepas lambat',
                'stok_minimum' => 12,
                'harga_beli' => 1100,
                'is_generik' => false,
            ],
            [
                'nama' => 'Insulin Glargine 100IU/mL',
                'kategori' => 'DM',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'SP',
                'sediaan' => 'SED-055',
                'komposisi' => 'Insulin glargine 100IU per mL',
                'indikasi' => 'Diabetes mellitus yang memerlukan insulin basal',
                'dosis' => 'Sesuai resep dokter',
                'kemasan' => 'Prefilled pen 3mL',
                'stok_minimum' => 5,
                'harga_beli' => 128000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Vitamin C 500mg',
                'kategori' => 'VIT',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Ascorbic acid 500mg',
                'indikasi' => 'Membantu memenuhi kebutuhan vitamin C',
                'dosis' => '1x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 35,
                'harga_beli' => 450,
                'is_generik' => true,
            ],
            [
                'nama' => 'Vitamin D3 1000IU Softgel',
                'kategori' => 'VIT',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'KPS',
                'sediaan' => 'SED-015',
                'komposisi' => 'Cholecalciferol 1000IU',
                'indikasi' => 'Membantu memenuhi kebutuhan vitamin D',
                'dosis' => '1x sehari 1 softgel',
                'kemasan' => 'Botol isi 30 softgel',
                'stok_minimum' => 15,
                'harga_beli' => 1800,
                'is_generik' => false,
            ],
            [
                'nama' => 'Vitamin B Complex Tablet',
                'kategori' => 'VIT',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Vitamin B1, B6, B12, dan vitamin B kompleks',
                'indikasi' => 'Membantu memenuhi kebutuhan vitamin B',
                'dosis' => '1x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 30,
                'harga_beli' => 500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Multivitamin Sirup Anak',
                'kategori' => 'VIT',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-022',
                'komposisi' => 'Vitamin A, B kompleks, C, D, dan E',
                'indikasi' => 'Suplemen vitamin untuk anak',
                'dosis' => '1-2x sehari 1 sendok takar',
                'kemasan' => 'Botol 60mL',
                'stok_minimum' => 12,
                'harga_beli' => 14500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Zinc 20mg',
                'kategori' => 'MNR',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Zinc sulfate monohydrate setara zinc 20mg',
                'indikasi' => 'Suplemen zinc dan terapi pendamping diare',
                'dosis' => '1x sehari 1 tablet sesuai kebutuhan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 480,
                'is_generik' => true,
            ],
            [
                'nama' => 'Calcium Lactate 500mg',
                'kategori' => 'MNR',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Calcium lactate 500mg',
                'indikasi' => 'Membantu memenuhi kebutuhan kalsium',
                'dosis' => '1-2x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 350,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ferrous Fumarate 60mg',
                'kategori' => 'HMT',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Ferrous fumarate setara elemental iron 60mg',
                'indikasi' => 'Membantu memenuhi kebutuhan zat besi',
                'dosis' => '1x sehari 1 tablet setelah makan',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 20,
                'harga_beli' => 400,
                'is_generik' => true,
            ],
            [
                'nama' => 'Folic Acid 1mg',
                'kategori' => 'HMT',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Folic acid 1mg',
                'indikasi' => 'Suplemen asam folat',
                'dosis' => '1x sehari 1 tablet',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 25,
                'harga_beli' => 300,
                'is_generik' => true,
            ],
            [
                'nama' => 'Aspirin 80mg',
                'kategori' => 'HMT',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Acetylsalicylic acid 80mg',
                'indikasi' => 'Antiplatelet sesuai indikasi dokter',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 15,
                'harga_beli' => 350,
                'is_generik' => true,
            ],
            [
                'nama' => 'Clopidogrel 75mg',
                'kategori' => 'HMT',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Clopidogrel bisulfate 75mg',
                'indikasi' => 'Antiplatelet sesuai indikasi dokter',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 12,
                'harga_beli' => 900,
                'is_generik' => true,
            ],
            [
                'nama' => 'Gabapentin 300mg',
                'kategori' => 'SRF',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Gabapentin 300mg',
                'indikasi' => 'Nyeri neuropatik dan terapi saraf sesuai resep',
                'dosis' => '1-3x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 10,
                'harga_beli' => 2300,
                'is_generik' => true,
            ],
            [
                'nama' => 'Mecobalamin 500mcg',
                'kategori' => 'SRF',
                'golongan' => 'OBK',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Mecobalamin 500mcg',
                'indikasi' => 'Neuropati perifer dan defisiensi vitamin B12',
                'dosis' => '3x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 15,
                'harga_beli' => 950,
                'is_generik' => true,
            ],
            [
                'nama' => 'Sertraline 50mg',
                'kategori' => 'PSD',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Sertraline HCl 50mg',
                'indikasi' => 'Gangguan depresi dan kecemasan sesuai resep dokter',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 6,
                'harga_beli' => 3200,
                'is_generik' => false,
            ],
            [
                'nama' => 'Risperidone 2mg',
                'kategori' => 'PSD',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Risperidone 2mg',
                'indikasi' => 'Terapi psikiatri sesuai resep dokter',
                'dosis' => '1-2x sehari sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 6,
                'harga_beli' => 1500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Meloxicam 7.5mg',
                'kategori' => 'ORM',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Meloxicam 7.5mg',
                'indikasi' => 'Nyeri dan peradangan sendi',
                'dosis' => '1x sehari 1 tablet sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 15,
                'harga_beli' => 600,
                'is_generik' => true,
            ],
            [
                'nama' => 'Diclofenac Sodium 50mg',
                'kategori' => 'ORM',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-004',
                'komposisi' => 'Diclofenac sodium 50mg',
                'indikasi' => 'Nyeri dan inflamasi',
                'dosis' => '2-3x sehari 1 tablet setelah makan sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet salut enterik',
                'stok_minimum' => 18,
                'harga_beli' => 450,
                'is_generik' => true,
            ],
            [
                'nama' => 'Allopurinol 100mg',
                'kategori' => 'OTP',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Allopurinol 100mg',
                'indikasi' => 'Hiperurisemia dan gout sesuai resep dokter',
                'dosis' => '1x sehari 1 tablet setelah makan sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 15,
                'harga_beli' => 300,
                'is_generik' => true,
            ],
            [
                'nama' => 'Glucosamine 500mg',
                'kategori' => 'OTP',
                'golongan' => 'FS',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Glucosamine sulfate 500mg',
                'indikasi' => 'Suplemen kesehatan sendi',
                'dosis' => '1-2x sehari 1 kapsul',
                'kemasan' => 'Botol isi 30 kapsul',
                'stok_minimum' => 10,
                'harga_beli' => 2500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Prednisone 5mg',
                'kategori' => 'HRM',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Prednisone 5mg',
                'indikasi' => 'Antiinflamasi kortikosteroid sesuai resep dokter',
                'dosis' => 'Sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 12,
                'harga_beli' => 250,
                'is_generik' => true,
            ],
            [
                'nama' => 'Levothyroxine 50mcg',
                'kategori' => 'HRM',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Levothyroxine sodium 50mcg',
                'indikasi' => 'Hipotiroid sesuai resep dokter',
                'dosis' => '1x sehari sebelum makan sesuai resep dokter',
                'kemasan' => 'Botol isi 100 tablet',
                'stok_minimum' => 8,
                'harga_beli' => 900,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ethinyl Estradiol Levonorgestrel Tablet',
                'kategori' => 'KBS',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Ethinyl estradiol 0.03mg + levonorgestrel 0.15mg',
                'indikasi' => 'Kontrasepsi oral',
                'dosis' => '1 tablet per hari sesuai petunjuk kemasan dan resep',
                'kemasan' => 'Blister isi 28 tablet',
                'stok_minimum' => 10,
                'harga_beli' => 14500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Medroxyprogesterone Injection 150mg/mL',
                'kategori' => 'KBS',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'AMP',
                'sediaan' => 'SED-054',
                'komposisi' => 'Medroxyprogesterone acetate 150mg per mL',
                'indikasi' => 'Kontrasepsi injeksi',
                'dosis' => 'Sesuai jadwal dan resep tenaga kesehatan',
                'kemasan' => 'Ampul 1mL',
                'stok_minimum' => 8,
                'harga_beli' => 18500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Tamsulosin 0.4mg',
                'kategori' => 'GIN',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'KPS',
                'sediaan' => 'SED-017',
                'komposisi' => 'Tamsulosin HCl 0.4mg',
                'indikasi' => 'Gejala hiperplasia prostat jinak',
                'dosis' => '1x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul lepas lambat',
                'stok_minimum' => 8,
                'harga_beli' => 3600,
                'is_generik' => false,
            ],
            [
                'nama' => 'Ciprofloxacin Eye Drops 0.3%',
                'kategori' => 'MTA',
                'golongan' => 'OBK',
                'satuan' => 'DROP',
                'sediaan' => 'SED-029',
                'komposisi' => 'Ciprofloxacin 0.3%',
                'indikasi' => 'Infeksi bakteri pada mata',
                'dosis' => 'Teteskan sesuai resep dokter',
                'kemasan' => 'Botol tetes 5mL',
                'stok_minimum' => 8,
                'harga_beli' => 9500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Artificial Tears Eye Drops',
                'kategori' => 'MTA',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'DROP',
                'sediaan' => 'SED-029',
                'komposisi' => 'Carboxymethylcellulose sodium 0.5%',
                'indikasi' => 'Mata kering dan iritasi ringan',
                'dosis' => '1-2 tetes pada mata bila perlu',
                'kemasan' => 'Botol tetes 10mL',
                'stok_minimum' => 12,
                'harga_beli' => 11000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Chloramphenicol Eye Ointment 1%',
                'kategori' => 'MTA',
                'golongan' => 'OBK',
                'satuan' => 'TUB',
                'sediaan' => 'SED-030',
                'komposisi' => 'Chloramphenicol 1%',
                'indikasi' => 'Infeksi bakteri pada mata',
                'dosis' => 'Oleskan sesuai resep dokter',
                'kemasan' => 'Tube 3.5g',
                'stok_minimum' => 8,
                'harga_beli' => 8200,
                'is_generik' => true,
            ],
            [
                'nama' => 'Hydrocortisone Cream 1%',
                'kategori' => 'KLT',
                'golongan' => 'OBK',
                'satuan' => 'TUB',
                'sediaan' => 'SED-039',
                'komposisi' => 'Hydrocortisone acetate 1%',
                'indikasi' => 'Radang dan gatal pada kulit',
                'dosis' => 'Oles tipis 2-3x sehari sesuai resep dokter',
                'kemasan' => 'Tube 5g',
                'stok_minimum' => 10,
                'harga_beli' => 4500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Betamethasone Cream 0.1%',
                'kategori' => 'KLT',
                'golongan' => 'OBK',
                'satuan' => 'TUB',
                'sediaan' => 'SED-039',
                'komposisi' => 'Betamethasone valerate 0.1%',
                'indikasi' => 'Dermatitis dan peradangan kulit sesuai resep',
                'dosis' => 'Oles tipis 1-2x sehari sesuai resep dokter',
                'kemasan' => 'Tube 5g',
                'stok_minimum' => 10,
                'harga_beli' => 6500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Miconazole Cream 2%',
                'kategori' => 'AJM',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TUB',
                'sediaan' => 'SED-039',
                'komposisi' => 'Miconazole nitrate 2%',
                'indikasi' => 'Infeksi jamur pada kulit',
                'dosis' => 'Oles tipis 2x sehari',
                'kemasan' => 'Tube 10g',
                'stok_minimum' => 12,
                'harga_beli' => 7500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ketoconazole Shampoo 2%',
                'kategori' => 'AJM',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-047',
                'komposisi' => 'Ketoconazole 2%',
                'indikasi' => 'Ketombe dan dermatitis seboroik',
                'dosis' => 'Gunakan 2-3x seminggu sesuai kebutuhan',
                'kemasan' => 'Botol 60mL',
                'stok_minimum' => 8,
                'harga_beli' => 26000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Acyclovir 400mg',
                'kategori' => 'AVS',
                'golongan' => 'OBK',
                'satuan' => 'TBL',
                'sediaan' => 'SED-001',
                'komposisi' => 'Acyclovir 400mg',
                'indikasi' => 'Infeksi virus herpes sesuai resep dokter',
                'dosis' => 'Sesuai resep dokter',
                'kemasan' => 'Strip isi 10 tablet',
                'stok_minimum' => 10,
                'harga_beli' => 900,
                'is_generik' => true,
            ],
            [
                'nama' => 'Oseltamivir 75mg',
                'kategori' => 'AVS',
                'golongan' => 'OBK',
                'main' => 'OKP',
                'satuan' => 'KPS',
                'sediaan' => 'SED-014',
                'komposisi' => 'Oseltamivir phosphate 75mg',
                'indikasi' => 'Terapi influenza sesuai resep dokter',
                'dosis' => '2x sehari 1 kapsul sesuai resep dokter',
                'kemasan' => 'Strip isi 10 kapsul',
                'stok_minimum' => 6,
                'harga_beli' => 8500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Albendazole 400mg',
                'kategori' => 'APT',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-005',
                'komposisi' => 'Albendazole 400mg',
                'indikasi' => 'Infeksi cacing',
                'dosis' => 'Dosis tunggal sesuai petunjuk kemasan',
                'kemasan' => 'Strip isi 1 tablet kunyah',
                'stok_minimum' => 20,
                'harga_beli' => 3500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Mebendazole 500mg',
                'kategori' => 'APT',
                'golongan' => 'OTC',
                'main' => 'OTG',
                'satuan' => 'TBL',
                'sediaan' => 'SED-005',
                'komposisi' => 'Mebendazole 500mg',
                'indikasi' => 'Infeksi cacing',
                'dosis' => 'Dosis tunggal sesuai petunjuk kemasan',
                'kemasan' => 'Strip isi 1 tablet kunyah',
                'stok_minimum' => 20,
                'harga_beli' => 3200,
                'is_generik' => true,
            ],
            [
                'nama' => 'Povidone Iodine 10%',
                'kategori' => 'ANS',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-049',
                'komposisi' => 'Povidone iodine 10%',
                'indikasi' => 'Antiseptik luka luar',
                'dosis' => 'Oleskan pada area yang dibersihkan',
                'kemasan' => 'Botol 60mL',
                'stok_minimum' => 15,
                'harga_beli' => 9500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Alcohol Swab',
                'kategori' => 'BMHP',
                'golongan' => 'ALK',
                'satuan' => 'PC',
                'sediaan' => 'SED-061',
                'komposisi' => 'Isopropyl alcohol 70%',
                'indikasi' => 'Pembersih kulit sebelum tindakan injeksi',
                'dosis' => 'Gunakan satu kali pakai',
                'kemasan' => 'Box isi 100 sachet',
                'stok_minimum' => 50,
                'harga_beli' => 180,
                'is_generik' => false,
            ],
            [
                'nama' => 'NaCl 0.9% Infus 500mL',
                'kategori' => 'INF',
                'golongan' => 'OBK',
                'satuan' => 'BAG',
                'sediaan' => 'SED-057',
                'komposisi' => 'Sodium chloride 0.9%',
                'indikasi' => 'Cairan infus elektrolit sesuai indikasi medis',
                'dosis' => 'Sesuai instruksi tenaga kesehatan',
                'kemasan' => 'Bag 500mL',
                'stok_minimum' => 20,
                'harga_beli' => 7500,
                'is_generik' => true,
            ],
            [
                'nama' => 'Ringer Lactate Infus 500mL',
                'kategori' => 'INF',
                'golongan' => 'OBK',
                'satuan' => 'BAG',
                'sediaan' => 'SED-057',
                'komposisi' => 'Ringer lactate solution',
                'indikasi' => 'Cairan infus elektrolit sesuai indikasi medis',
                'dosis' => 'Sesuai instruksi tenaga kesehatan',
                'kemasan' => 'Bag 500mL',
                'stok_minimum' => 20,
                'harga_beli' => 8200,
                'is_generik' => true,
            ],
            [
                'nama' => 'Blood Glucose Test Strip',
                'kategori' => 'DGN',
                'golongan' => 'ALK',
                'satuan' => 'STR',
                'sediaan' => 'SED-060',
                'komposisi' => 'Strip uji glukosa darah',
                'indikasi' => 'Pemantauan kadar gula darah',
                'dosis' => 'Gunakan sesuai alat dan petunjuk kemasan',
                'kemasan' => 'Box isi 25 strip',
                'stok_minimum' => 10,
                'harga_beli' => 2200,
                'is_generik' => false,
            ],
            [
                'nama' => 'Rapid Test Kit Antigen',
                'kategori' => 'DGN',
                'golongan' => 'ALK',
                'satuan' => 'KIT',
                'sediaan' => 'SED-060',
                'komposisi' => 'Kit diagnostik antigen',
                'indikasi' => 'Pemeriksaan antigen sesuai petunjuk penggunaan',
                'dosis' => 'Gunakan satu kali pakai',
                'kemasan' => 'Box isi 20 kit',
                'stok_minimum' => 8,
                'harga_beli' => 8500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Thermometer Digital',
                'kategori' => 'ALK',
                'golongan' => 'ALK',
                'satuan' => 'PC',
                'sediaan' => 'SED-061',
                'komposisi' => 'Thermometer digital',
                'indikasi' => 'Pengukuran suhu tubuh',
                'dosis' => 'Gunakan sesuai petunjuk alat',
                'kemasan' => 'Box isi 1 unit',
                'stok_minimum' => 6,
                'harga_beli' => 18000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Masker Medis 3 Ply',
                'kategori' => 'BMHP',
                'golongan' => 'ALK',
                'satuan' => 'BOX',
                'sediaan' => 'SED-061',
                'komposisi' => 'Masker medis tiga lapis',
                'indikasi' => 'Perlindungan pernapasan dasar',
                'dosis' => 'Gunakan satu kali pakai',
                'kemasan' => 'Box isi 50 pcs',
                'stok_minimum' => 10,
                'harga_beli' => 21000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Kasa Steril 16x16',
                'kategori' => 'BMHP',
                'golongan' => 'ALK',
                'satuan' => 'BOX',
                'sediaan' => 'SED-061',
                'komposisi' => 'Kasa steril',
                'indikasi' => 'Penutup luka dan tindakan perawatan luka',
                'dosis' => 'Gunakan sesuai kebutuhan tindakan',
                'kemasan' => 'Box isi 50 lembar',
                'stok_minimum' => 10,
                'harga_beli' => 32000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Plester Hypoallergenic',
                'kategori' => 'P3K',
                'golongan' => 'ALK',
                'satuan' => 'RLL',
                'sediaan' => 'SED-061',
                'komposisi' => 'Plester perekat hipoalergenik',
                'indikasi' => 'Fiksasi kasa dan balutan luka',
                'dosis' => 'Gunakan sesuai kebutuhan',
                'kemasan' => 'Roll 1.25cm x 5m',
                'stok_minimum' => 12,
                'harga_beli' => 8500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Baby Oil 100mL',
                'kategori' => 'PBD',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-044',
                'komposisi' => 'Mineral oil dan fragrance',
                'indikasi' => 'Perawatan kulit bayi',
                'dosis' => 'Gunakan secukupnya pada kulit',
                'kemasan' => 'Botol 100mL',
                'stok_minimum' => 10,
                'harga_beli' => 14500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Minyak Telon 60mL',
                'kategori' => 'HBL',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-044',
                'komposisi' => 'Oleum cajuputi, oleum anisi, dan oleum cocos',
                'indikasi' => 'Membantu menghangatkan tubuh',
                'dosis' => 'Oleskan secukupnya pada kulit',
                'kemasan' => 'Botol 60mL',
                'stok_minimum' => 12,
                'harga_beli' => 12500,
                'is_generik' => false,
            ],
            [
                'nama' => 'Susu Formula Bayi 0-6 Bulan',
                'kategori' => 'NTR',
                'golongan' => 'MNT',
                'satuan' => 'KLG',
                'sediaan' => 'SED-062',
                'komposisi' => 'Nutrisi bayi bubuk dengan vitamin dan mineral',
                'indikasi' => 'Nutrisi bayi sesuai kebutuhan',
                'dosis' => 'Sesuai petunjuk penyajian',
                'kemasan' => 'Kaleng 400g',
                'stok_minimum' => 8,
                'harga_beli' => 78000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Nutrisi Diabetes Powder',
                'kategori' => 'NTR',
                'golongan' => 'MNT',
                'satuan' => 'KLG',
                'sediaan' => 'SED-062',
                'komposisi' => 'Formula nutrisi rendah indeks glikemik',
                'indikasi' => 'Nutrisi pendamping untuk kebutuhan diabetes',
                'dosis' => 'Sesuai petunjuk penyajian',
                'kemasan' => 'Kaleng 400g',
                'stok_minimum' => 6,
                'harga_beli' => 92000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Chlorhexidine Mouthwash 0.2%',
                'kategori' => 'ORL',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'BTL',
                'sediaan' => 'SED-050',
                'komposisi' => 'Chlorhexidine gluconate 0.2%',
                'indikasi' => 'Membantu menjaga kebersihan mulut',
                'dosis' => 'Kumur 2x sehari sesuai petunjuk kemasan',
                'kemasan' => 'Botol 100mL',
                'stok_minimum' => 10,
                'harga_beli' => 18000,
                'is_generik' => false,
            ],
            [
                'nama' => 'Fluoride Toothpaste',
                'kategori' => 'ORL',
                'golongan' => 'OTC',
                'main' => 'OTP',
                'satuan' => 'TUB',
                'sediaan' => 'SED-042',
                'komposisi' => 'Sodium fluoride',
                'indikasi' => 'Perawatan gigi dan pencegahan karies',
                'dosis' => 'Gunakan saat menyikat gigi',
                'kemasan' => 'Tube 120g',
                'stok_minimum' => 10,
                'harga_beli' => 13000,
                'is_generik' => false,
            ],
        ];
    }
}
