<style>
    .sales-return-page { --sr-primary:#3157a4; --sr-navy:#172a50; --sr-soft:#edf3ff; color:#26344e; }
    .sales-return-hero { position:relative; overflow:hidden; display:grid; grid-template-columns:minmax(0,1fr) minmax(420px,.9fr); gap:32px; padding:32px; border-radius:20px; color:#fff; background:linear-gradient(130deg,#182d56 0%,#315ca9 58%,#4084c5 100%); box-shadow:0 18px 45px rgba(32,66,128,.2); }
    .sales-return-hero::after { content:""; position:absolute; width:270px; height:270px; right:-90px; top:-120px; border-radius:50%; border:42px solid rgba(255,255,255,.08); }
    .sales-return-hero h1 { margin:6px 0 8px; font-size:2rem; font-weight:750; color:#fff; }
    .sales-return-hero p { max-width:700px; margin:0; color:rgba(255,255,255,.8); line-height:1.65; }
    .sales-return-kicker,.sales-return-modal-kicker { font-size:.72rem; text-transform:uppercase; letter-spacing:.16em; font-weight:750; }
    .sales-return-kicker i { font-size:1rem; margin-right:6px; }
    .sales-return-flow { position:relative; z-index:1; display:flex; align-items:center; align-self:center; padding:18px; border:1px solid rgba(255,255,255,.16); border-radius:16px; background:rgba(255,255,255,.09); backdrop-filter:blur(8px); }
    .sales-return-flow>div { flex:1; min-width:0; }
    .sales-return-flow>div>span { display:inline-grid; place-items:center; width:25px; height:25px; margin-bottom:8px; border-radius:8px; background:#fff; color:var(--sr-primary); font-weight:800; }
    .sales-return-flow strong,.sales-return-flow small { display:block; }
    .sales-return-flow strong { font-size:.82rem; }
    .sales-return-flow small { margin-top:4px; color:rgba(255,255,255,.68); font-size:.69rem; line-height:1.45; }
    .sales-return-flow>i { margin:0 8px; color:rgba(255,255,255,.5); }
    .sales-return-stats { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:16px; margin:20px 0; }
    .sales-return-stats article { display:flex; align-items:center; gap:14px; min-height:112px; padding:18px; border:1px solid #e5eaf2; border-radius:16px; background:#fff; box-shadow:0 8px 24px rgba(31,48,81,.06); }
    .sales-return-stats article>i { display:grid; place-items:center; width:48px; height:48px; flex:0 0 48px; border-radius:14px; background:#edf3ff; color:#3157a4; font-size:1.45rem; }
    .sales-return-stats .is-warning>i { background:#fff5dc; color:#b77910; }.sales-return-stats .is-success>i { background:#e9f8f0; color:#26835a; }.sales-return-stats .is-value>i { background:#f1edff; color:#6c4bc2; }
    .sales-return-stats small,.sales-return-stats span { display:block; color:#7b879d; }.sales-return-stats strong { display:block; margin:2px 0; color:#1e2f50; font-size:1.35rem; }.sales-return-stats span { font-size:.72rem; }
    .sales-return-panel { overflow:hidden; border:1px solid #e4e9f2; border-radius:18px; background:#fff; box-shadow:0 12px 34px rgba(30,49,85,.07); }
    .sales-return-toolbar,.sales-return-filters { display:flex; align-items:center; justify-content:space-between; gap:18px; padding:20px 22px; }
    .sales-return-toolbar { border-bottom:1px solid #edf0f5; }.sales-return-toolbar h2 { margin:0 0 3px; color:#203458; font-size:1.08rem; font-weight:750; }.sales-return-toolbar p { margin:0; color:#7a879a; font-size:.78rem; }
    .sales-return-toolbar-actions,.sales-return-filter-fields,.sales-return-chips { display:flex; align-items:center; gap:9px; }
    .sales-return-search { position:relative; min-width:290px; }.sales-return-search i { position:absolute; left:12px; top:50%; transform:translateY(-50%); color:#8290a6; }.sales-return-search input { width:100%; height:38px; padding:0 12px 0 37px; border:1px solid #dce3ed; border-radius:10px; outline:0; }.sales-return-search input:focus { border-color:#7193d1; box-shadow:0 0 0 3px rgba(49,87,164,.1); }
    .sales-return-filters { padding-top:14px; padding-bottom:14px; background:#f8faff; }.sales-return-chips button { padding:7px 13px; border:1px solid #dce4ef; border-radius:999px; color:#607089; background:#fff; font-size:.76rem; font-weight:650; }.sales-return-chips button.is-active { border-color:#3157a4; color:#fff; background:#3157a4; }.sales-return-filter-fields .form-control,.sales-return-filter-fields .form-select { min-width:140px; height:36px; font-size:.78rem; }
    .sales-return-table { margin:0; }.sales-return-table thead th { padding:13px 16px; border:0; background:#f1f5fb; color:#61708a; font-size:.68rem; text-transform:uppercase; letter-spacing:.05em; white-space:nowrap; }.sales-return-table tbody td { padding:14px 16px; border-color:#edf0f5; vertical-align:middle; }.sales-return-table strong,.sales-return-table small { display:block; }.sales-return-table small { margin-top:3px; color:#8490a2; font-size:.72rem; }
    .sales-return-status { display:inline-flex; align-items:center; padding:4px 9px; margin-top:6px; border-radius:999px; font-size:.66rem; font-weight:750; }.sales-return-status.is-draft { color:#9a6911; background:#fff3d7; }.sales-return-status.is-posted { color:#257a54; background:#e5f7ed; }.sales-return-status.is-cancelled { color:#a5404b; background:#fdebed; }
    .sales-return-actions { display:flex; justify-content:flex-end; gap:5px; }.sales-return-actions button { display:grid; place-items:center; width:32px; height:32px; padding:0; border:1px solid #dfe5ee; border-radius:9px; color:#50617c; background:#fff; }.sales-return-actions button:hover { border-color:#3157a4; color:#3157a4; }.sales-return-actions .is-danger:hover { border-color:#cf5663; color:#cf5663; }
    .sales-return-modal { border:0; border-radius:18px; overflow:hidden; }.sales-return-modal .modal-header { padding:18px 22px; border-bottom:1px solid #e7ebf2; background:#f8faff; }.sales-return-modal-kicker { display:block; margin-bottom:3px; color:#6f81a1; }.sales-return-modal .modal-title { color:#203458; font-weight:750; }.sales-return-modal .modal-body { padding:22px; background:#fbfcfe; }
    .sales-return-form-grid { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:16px; }.sales-return-field.is-wide { grid-column:span 2; }.sales-return-field label { display:block; margin-bottom:6px; color:#42516a; font-size:.76rem; font-weight:700; }.sales-return-field label span { color:#cf4d5b; }.sales-return-field small { display:block; margin-top:5px; color:#8a95a7; font-size:.68rem; }
    .sales-return-transaction-card { display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); gap:12px; margin-top:20px; padding:16px; border:1px solid #dce5f2; border-radius:14px; background:#eef4ff; }.sales-return-transaction-card div small,.sales-return-transaction-card div strong { display:block; }.sales-return-transaction-card div small { color:#73819a; font-size:.67rem; text-transform:uppercase; }.sales-return-transaction-card div strong { margin-top:3px; color:#273b61; font-size:.82rem; }
    .sales-return-items-section { margin-top:22px; border:1px solid #e1e6ef; border-radius:14px; overflow:hidden; background:#fff; }.sales-return-section-title { display:flex; justify-content:space-between; align-items:center; padding:15px 16px; border-bottom:1px solid #e7ebf2; }.sales-return-section-title h6 { margin:0 0 2px; color:#263a5e; font-weight:750; }.sales-return-section-title p { margin:0; color:#8490a2; font-size:.72rem; }
    .sales-return-items-table { margin:0; }.sales-return-items-table th { padding:10px 12px; border:0; background:#f4f7fb; color:#687790; font-size:.66rem; text-transform:uppercase; white-space:nowrap; }.sales-return-items-table td { padding:12px; border-color:#edf0f5; vertical-align:middle; font-size:.76rem; }.sales-return-items-table td strong,.sales-return-items-table td small { display:block; }.sales-return-items-table td small { color:#8792a5; }.sales-return-items-table .form-control { min-width:90px; font-size:.76rem; }.sales-return-items-table input[type=checkbox] { width:17px; height:17px; accent-color:#3157a4; }
    .sales-return-modal-footer { display:flex; justify-content:space-between; padding:15px 22px; }.sales-return-form-total small,.sales-return-form-total strong,.sales-return-form-total span { display:block; }.sales-return-form-total small,.sales-return-form-total span { color:#7f8ba0; font-size:.68rem; }.sales-return-form-total strong { color:#244b91; font-size:1.15rem; }.sales-return-modal-footer>div:last-child { display:flex; align-items:center; gap:8px; }
    .sales-return-detail-grid { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:12px; margin-bottom:18px; }.sales-return-detail-info { padding:13px; border:1px solid #e2e7ef; border-radius:11px; background:#fff; }.sales-return-detail-info small,.sales-return-detail-info strong { display:block; }.sales-return-detail-info small { color:#8490a2; font-size:.68rem; text-transform:uppercase; }.sales-return-detail-info strong { margin-top:4px; color:#2d405f; font-size:.82rem; }
    .sales-return-detail-total { margin-left:auto; max-width:390px; padding:14px; border-radius:12px; background:#eef4ff; }.sales-return-detail-total div { display:flex; justify-content:space-between; padding:4px 0; font-size:.78rem; }.sales-return-detail-total div:last-child { margin-top:5px; padding-top:9px; border-top:1px solid #cfdbef; color:#214a91; font-size:.95rem; font-weight:800; }

    /* Premium modal workspace */
    .modal-backdrop.show { opacity:.64; backdrop-filter:blur(5px); }
    .sales-return-modal-root { padding:0 !important; }
    .sales-return-dialog { width:auto; max-width:min(1420px,calc(100vw - 32px)); height:calc(100vh - 32px); height:calc(100dvh - 32px); min-height:520px; margin:16px auto; }
    .modal-dialog-scrollable.sales-return-dialog .sales-return-modal { width:100%; height:100%; max-height:none; min-height:0; border:1px solid rgba(255,255,255,.22); border-radius:24px; overflow:hidden; background:#f7f9fc; box-shadow:0 32px 90px rgba(8,20,45,.38),0 8px 24px rgba(8,20,45,.18); }
    .sales-return-form-shell { display:flex; flex:1 1 auto; flex-direction:column; width:100%; height:100%; min-height:0; overflow:hidden; }
    .sales-return-modal .modal-header { position:relative; z-index:5; display:flex; flex:0 0 auto; align-items:center; justify-content:space-between; gap:24px; min-height:92px; padding:18px 24px; border:0; color:#fff; background:radial-gradient(circle at 78% -80%,rgba(104,163,255,.42),transparent 42%),linear-gradient(125deg,#132442 0%,#1f4076 55%,#2d64aa 100%); box-shadow:0 8px 30px rgba(16,37,73,.18); }
    .sales-return-modal .modal-header::after { content:""; position:absolute; right:17%; bottom:0; width:170px; height:2px; background:linear-gradient(90deg,transparent,rgba(143,194,255,.85),transparent); }
    .sales-return-modal-brand { display:flex; align-items:center; gap:14px; min-width:0; }
    .sales-return-modal-icon { display:grid; place-items:center; width:50px; height:50px; flex:0 0 50px; border:1px solid rgba(255,255,255,.22); border-radius:15px; color:#fff; background:linear-gradient(145deg,rgba(255,255,255,.22),rgba(255,255,255,.08)); box-shadow:inset 0 1px 0 rgba(255,255,255,.2),0 10px 24px rgba(3,17,42,.18); font-size:1.45rem; }
    .sales-return-modal .sales-return-modal-kicker { margin-bottom:3px; color:#aecdff; font-size:.65rem; letter-spacing:.18em; }
    .sales-return-modal .modal-title { color:#fff; font-size:1.14rem; font-weight:780; letter-spacing:-.01em; }
    .sales-return-modal-brand p { margin:3px 0 0; color:rgba(255,255,255,.68); font-size:.72rem; }
    .sales-return-modal-progress { display:flex; align-items:center; gap:8px; margin-left:auto; padding:8px 12px; border:1px solid rgba(255,255,255,.12); border-radius:999px; background:rgba(7,24,52,.18); }
    .sales-return-modal-progress span { display:flex; align-items:center; gap:6px; color:rgba(255,255,255,.58); font-size:.68rem; font-weight:700; white-space:nowrap; }
    .sales-return-modal-progress span b { display:grid; place-items:center; width:22px; height:22px; border-radius:50%; color:#b9d5ff; background:rgba(255,255,255,.11); font-size:.65rem; }
    .sales-return-modal-progress span.is-active { color:#fff; }.sales-return-modal-progress span.is-active b { color:#244a81; background:#fff; box-shadow:0 4px 12px rgba(5,22,50,.2); }
    .sales-return-modal-progress>i { color:rgba(255,255,255,.32); }
    .sales-return-modal .modal-header .btn-close { width:36px; height:36px; flex:0 0 36px; margin:0; padding:0; border-radius:11px; background-color:rgba(255,255,255,.1); background-size:12px; opacity:.82; transition:background-color .18s ease,opacity .18s ease,transform .18s ease; }
    .sales-return-modal .modal-header .btn-close:hover { background-color:rgba(255,255,255,.18); opacity:1; transform:rotate(4deg); }
    .modal-dialog-scrollable.sales-return-dialog .sales-return-modal .modal-body { flex:1 1 auto; min-height:0; padding:22px 24px 32px; overflow-x:hidden !important; overflow-y:auto !important; overscroll-behavior:contain; -webkit-overflow-scrolling:touch; touch-action:pan-y; background:linear-gradient(180deg,#f4f7fb 0,#fbfcfe 190px); scrollbar-width:thin; scrollbar-color:#9eb0cc transparent; }
    .modal-dialog-scrollable.sales-return-dialog .sales-return-modal .modal-body::-webkit-scrollbar { width:9px; }.modal-dialog-scrollable.sales-return-dialog .sales-return-modal .modal-body::-webkit-scrollbar-track { background:transparent; }.modal-dialog-scrollable.sales-return-dialog .sales-return-modal .modal-body::-webkit-scrollbar-thumb { border:2px solid transparent; border-radius:999px; background-clip:padding-box; background-color:#9eb0cc; }
    .sales-return-form-card { padding:20px; border:1px solid #e1e7f0; border-radius:18px; background:rgba(255,255,255,.94); box-shadow:0 10px 30px rgba(31,51,84,.055),inset 0 1px 0 #fff; }
    .sales-return-card-heading { display:flex; align-items:center; gap:11px; margin-bottom:18px; }.sales-return-card-heading>span { display:grid; place-items:center; width:38px; height:38px; flex:0 0 38px; border-radius:11px; color:#315ca7; background:linear-gradient(145deg,#eef4ff,#dce9ff); font-size:1.12rem; }.sales-return-card-heading h6 { margin:0 0 2px; color:#203557; font-size:.88rem; font-weight:780; }.sales-return-card-heading p { margin:0; color:#8490a3; font-size:.7rem; }.sales-return-card-heading.is-compact { margin:0; }
    .sales-return-form-grid { gap:17px; }
    .sales-return-field label { margin-bottom:7px; color:#344761; font-size:.72rem; letter-spacing:.01em; }
    .sales-return-field .form-control,.sales-return-field .form-select { min-height:44px; border:1px solid #d9e1ec; border-radius:11px; color:#2c3f5e; background-color:#fff; box-shadow:0 1px 2px rgba(25,43,73,.025); font-size:.8rem; transition:border-color .18s ease,box-shadow .18s ease,background-color .18s ease; }
    .sales-return-field textarea.form-control { min-height:70px; padding-top:10px; resize:vertical; }
    .sales-return-field .form-control:focus,.sales-return-field .form-select:focus { border-color:#648bd0; background:#fff; box-shadow:0 0 0 3px rgba(49,87,164,.11); }
    .sales-return-field .form-control[readonly] { color:#60708a; background:#f5f7fa; }
    .sales-return-input-icon { position:relative; }.sales-return-input-icon>i { position:absolute; z-index:2; top:50%; left:13px; transform:translateY(-50%); color:#8090aa; font-size:1rem; pointer-events:none; }.sales-return-input-icon>.form-control { padding-left:38px; }
    #salesReturnModal .select2-container .select2-selection--single { height:44px; border:1px solid #d9e1ec; border-radius:11px; }.sales-return-modal-root .select2-container--default .select2-selection--single .select2-selection__rendered { padding-left:13px; line-height:42px; color:#2c3f5e; font-size:.8rem; }.sales-return-modal-root .select2-container--default .select2-selection--single .select2-selection__arrow { height:42px; right:8px; }.sales-return-modal-root .select2-dropdown { overflow:hidden; border:1px solid #d5deeb; border-radius:12px; box-shadow:0 16px 40px rgba(24,43,78,.16); }.sales-return-modal-root .select2-results__option { padding:9px 12px; }.sales-return-modal-root .select2-search--dropdown .select2-search__field { border:1px solid #d5deeb; border-radius:9px; }
    .sales-return-transaction-card { position:relative; margin-top:16px; padding:16px 18px; border:1px solid #ccdcee; border-radius:16px; background:linear-gradient(115deg,#eaf2ff 0%,#f5f9ff 72%,#edf5ff 100%); box-shadow:0 8px 24px rgba(48,86,146,.07); }
    .sales-return-transaction-card::before { content:""; position:absolute; top:14px; bottom:14px; left:0; width:3px; border-radius:0 4px 4px 0; background:linear-gradient(#3e72bf,#65a0e0); }
    .sales-return-transaction-card div { min-width:0; padding:2px 8px; }.sales-return-transaction-card div+div { border-left:1px solid rgba(92,123,169,.14); }.sales-return-transaction-card div small { color:#70819b; letter-spacing:.06em; }.sales-return-transaction-card div strong { overflow:hidden; color:#203b67; text-overflow:ellipsis; white-space:nowrap; }
    .sales-return-items-section { margin-top:16px; border-color:#dfe6f0; border-radius:18px; box-shadow:0 10px 30px rgba(31,51,84,.055); }
    .sales-return-section-title { min-height:68px; padding:13px 16px; background:linear-gradient(180deg,#fff,#fbfcfe); }
    .sales-return-section-title .btn { border-radius:10px; font-size:.72rem; font-weight:700; }
    .sales-return-items-scroll { overflow-x:auto; scrollbar-width:thin; scrollbar-color:#b0bdd0 transparent; }
    .sales-return-items-table { min-width:1080px; }
    .sales-return-items-table th { position:sticky; top:0; z-index:2; padding:11px 12px; color:#64748c; background:#f0f4f9; font-size:.63rem; letter-spacing:.055em; }
    .sales-return-items-table td { padding:13px 12px; background:#fff; }.sales-return-items-table tbody tr { transition:background-color .16s ease,box-shadow .16s ease; }.sales-return-items-table tbody tr:hover td { background:#f9fbff; }.sales-return-items-table tbody tr:has(.return-item-check:checked) td { background:#f3f7ff; }.sales-return-items-table tbody tr:has(.return-item-check:checked) { box-shadow:inset 3px 0 #4272bd; }
    .sales-return-items-table .return-item-qty { min-width:92px; height:38px; border-radius:9px; text-align:right; }.sales-return-items-table .return-item-reason { min-width:180px; height:38px; border-radius:9px; }
    .sales-return-items-table input:disabled { color:#9ba6b6; background:#f3f5f8; }
    .sales-return-modal .modal-footer { position:relative; z-index:5; display:flex; flex:0 0 auto; align-items:center; gap:20px; min-height:78px; padding:13px 24px; border:0; border-top:1px solid #e0e6ef; background:rgba(255,255,255,.96); box-shadow:0 -12px 28px rgba(26,44,73,.07); backdrop-filter:blur(12px); }
    .sales-return-footer-note { display:flex; align-items:center; gap:10px; margin-right:auto; }.sales-return-footer-note>i { display:grid; place-items:center; width:38px; height:38px; border-radius:11px; color:#26805a; background:#e7f7ef; font-size:1.15rem; }.sales-return-footer-note span,.sales-return-footer-note strong,.sales-return-footer-note small { display:block; }.sales-return-footer-note strong { color:#32475f; font-size:.72rem; }.sales-return-footer-note small { margin-top:1px; color:#8793a5; font-size:.64rem; }
    .sales-return-form-total { min-width:190px; padding:3px 18px; border-right:1px solid #e0e6ee; border-left:1px solid #e0e6ee; text-align:right; }.sales-return-form-total strong { margin:1px 0; font-size:1.2rem; letter-spacing:-.025em; }.sales-return-footer-actions { display:flex; align-items:center; gap:9px; }.sales-return-footer-actions .btn { min-height:42px; padding:9px 18px; border-radius:11px; font-size:.78rem; font-weight:700; }.sales-return-footer-actions .btn-primary { border-color:#315ca7; background:linear-gradient(135deg,#315ca7,#4076be); box-shadow:0 7px 18px rgba(49,92,167,.2); }
    .sales-return-detail-dialog { max-width:min(1220px,calc(100vw - 32px)); }.sales-return-detail-dialog .sales-return-modal>.modal-body { padding-top:24px; }.sales-return-detail-dialog .sales-return-modal>.modal-footer { justify-content:flex-end; min-height:66px; }

    @media(max-width:1100px){
        .sales-return-hero{grid-template-columns:1fr}.sales-return-stats{grid-template-columns:repeat(2,1fr)}
        .sales-return-form-grid{grid-template-columns:repeat(2,1fr)}.sales-return-transaction-card{grid-template-columns:repeat(3,1fr)}
        .sales-return-modal-progress{display:none}.sales-return-footer-note{display:none}.sales-return-form-total{margin-left:auto}
    }
    @media(max-width:767px){
        .sales-return-hero{padding:22px}.sales-return-flow{display:none}.sales-return-stats{grid-template-columns:1fr}.sales-return-toolbar,.sales-return-filters{align-items:stretch;flex-direction:column}.sales-return-toolbar-actions,.sales-return-filter-fields{align-items:stretch;flex-wrap:wrap}.sales-return-search{min-width:100%}
        .sales-return-dialog,.sales-return-detail-dialog{width:100%;max-width:none;height:100vh;height:100dvh;min-height:0;margin:0}
        .modal-dialog-scrollable.sales-return-dialog .sales-return-modal{height:100vh;height:100dvh;border:0;border-radius:0}
        .sales-return-modal .modal-header{min-height:74px;padding:12px 14px;gap:10px}.sales-return-modal-icon{width:42px;height:42px;flex-basis:42px;border-radius:12px;font-size:1.2rem}.sales-return-modal-brand p{display:none}.sales-return-modal .modal-title{font-size:1rem}.sales-return-modal .sales-return-modal-kicker{font-size:.57rem}.sales-return-modal .modal-header .btn-close{width:34px;height:34px;flex-basis:34px}
        .modal-dialog-scrollable.sales-return-dialog .sales-return-modal .modal-body{padding:14px 12px 110px}.sales-return-form-card{padding:15px;border-radius:15px}.sales-return-card-heading{margin-bottom:14px}
        .sales-return-form-grid{grid-template-columns:1fr;gap:13px}.sales-return-field.is-wide{grid-column:span 1}.sales-return-transaction-card,.sales-return-detail-grid{grid-template-columns:1fr 1fr}.sales-return-transaction-card{gap:8px;padding:13px 11px}.sales-return-transaction-card div+div{border-left:0}.sales-return-transaction-card div{padding:3px 5px}
        .sales-return-section-title{align-items:flex-start;gap:10px;padding:12px}.sales-return-section-title .sales-return-card-heading>span{display:none}.sales-return-section-title .btn{flex:0 0 auto;padding:7px 9px}.sales-return-card-heading.is-compact{align-items:flex-start}.sales-return-card-heading.is-compact p{max-width:190px}
        .sales-return-items-scroll{overflow:visible}.sales-return-items-table{display:block;min-width:0}.sales-return-items-table thead{display:none}.sales-return-items-table tbody{display:block;padding:10px;background:#f4f7fb}.sales-return-items-table tbody tr.sales-return-item-row{position:relative;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-bottom:10px;padding:12px;border:1px solid #e0e6ef;border-radius:14px;background:#fff;box-shadow:0 5px 16px rgba(34,52,82,.055)}.sales-return-items-table tbody tr.sales-return-item-row:last-child{margin-bottom:0}.sales-return-items-table tbody tr.sales-return-item-row:hover td,.sales-return-items-table tbody tr.sales-return-item-row:has(.return-item-check:checked) td{background:transparent}.sales-return-items-table tbody tr.sales-return-item-row:has(.return-item-check:checked){border-color:#9bb5de;background:#f5f8ff;box-shadow:inset 3px 0 #4272bd,0 6px 18px rgba(49,87,164,.08)}
        .sales-return-items-table tbody tr.sales-return-item-row td{display:flex;align-items:center;justify-content:space-between;gap:8px;min-width:0;padding:7px 8px;border:0;border-radius:9px;background:#f7f9fc;font-size:.72rem}.sales-return-items-table tbody tr.sales-return-item-row td::before{content:attr(data-label);color:#7c899d;font-size:.61rem;font-weight:700;text-transform:uppercase}.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(1){position:absolute;top:14px;left:13px;z-index:2;width:22px;padding:0;background:transparent}.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(1)::before{display:none}.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(2){display:block;grid-column:1/-1;padding:2px 4px 10px 38px;background:transparent}.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(2)::before{display:none}.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(2) strong{font-size:.78rem}.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(6),.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(8){grid-column:1/-1}.sales-return-items-table tbody tr.sales-return-item-row td:nth-child(7){grid-column:1/-1;background:#eaf2ff}.sales-return-items-table .return-item-qty,.sales-return-items-table .return-item-reason{width:58%;min-width:0}.sales-return-items-table .return-item-reason{width:66%}
        #salesReturnItems tr:not(.sales-return-item-row){display:block}#salesReturnItems tr:not(.sales-return-item-row) td{display:block;width:100%;padding:28px 12px}
        .sales-return-detail-items-table{display:table;min-width:900px}.sales-return-detail-items-table thead{display:table-header-group}.sales-return-detail-items-table tbody{display:table-row-group;padding:0;background:#fff}.sales-return-detail-items-table tbody tr{display:table-row}.sales-return-detail-items-table tbody td{display:table-cell}
        .sales-return-modal .modal-footer{position:absolute;right:0;bottom:0;left:0;gap:10px;min-height:88px;padding:11px 12px calc(11px + env(safe-area-inset-bottom));}.sales-return-form-total{min-width:0;margin:0 auto 0 0;padding:0 10px 0 0;border:0;text-align:left}.sales-return-form-total strong{font-size:1rem}.sales-return-form-total span{display:none}.sales-return-footer-actions{gap:7px}.sales-return-footer-actions .btn{min-height:40px;padding:8px 12px}.sales-return-detail-dialog .sales-return-modal>.modal-footer{position:absolute;min-height:66px}
        .sales-return-detail-total{max-width:none;margin-left:0}
    }
    @media(max-width:480px){
        .sales-return-transaction-card,.sales-return-detail-grid{grid-template-columns:1fr}.sales-return-modal .modal-header{padding-right:10px}.sales-return-modal-icon{display:none}.sales-return-form-total small{font-size:.6rem}.sales-return-footer-actions .btn{padding:8px 10px;font-size:.7rem}.sales-return-footer-actions .btn-light{display:none}
    }
</style>
