<style>
    .profitability-page {
        --pa-ink: #142b3b; --pa-muted: #718592; --pa-border: #e1e9ec; --pa-soft: #f5f8f9;
        --pa-green: #0b9b77; --pa-teal: #087f79; --pa-navy: #163d5a; --pa-blue: #3478f6;
        --pa-violet: #7559d7; --pa-orange: #d57b2a; color: var(--pa-ink); padding-bottom: 36px;
    }
    .pa-hero { position: relative; display: grid; grid-template-columns: minmax(0,1.6fr) minmax(280px,.7fr); gap: 28px; overflow: hidden; min-height: 300px; border-radius: 25px; padding: 42px; color: #fff; background: linear-gradient(128deg,#102f49 0%,#075f67 55%,#0c8d78 100%); box-shadow: 0 24px 60px rgba(18,54,70,.2); }
    .pa-hero::before { content: ""; position: absolute; width: 380px; height: 380px; right: -115px; top: -175px; border: 1px solid rgba(255,255,255,.16); border-radius: 50%; box-shadow: 0 0 0 52px rgba(255,255,255,.035),0 0 0 110px rgba(255,255,255,.025); }
    .pa-hero::after { content: ""; position: absolute; inset: auto 0 0; height: 90px; opacity: .16; background: linear-gradient(120deg,transparent 20%,rgba(255,255,255,.22)); clip-path: polygon(0 88%,20% 38%,39% 72%,59% 20%,78% 53%,100% 2%,100% 100%,0 100%); }
    .pa-hero-copy,.pa-hero-score { position: relative; z-index: 1; }
    .pa-eyebrow { display: inline-flex; align-items: center; gap: 7px; border: 1px solid rgba(255,255,255,.18); border-radius: 999px; padding: 7px 12px; color: #c9fff2; background: rgba(255,255,255,.08); font-size: 11px; font-weight: 900; letter-spacing: .12em; text-transform: uppercase; }
    .pa-hero h1 { max-width: 700px; margin: 18px 0 13px; font-size: clamp(31px,4vw,53px); font-weight: 780; line-height: 1.05; letter-spacing: -.05em; }
    .pa-hero-copy > p { max-width: 690px; margin: 0; color: rgba(238,255,252,.78); font-size: 14px; line-height: 1.7; }
    .pa-hero-chips { display: flex; flex-wrap: wrap; gap: 9px; margin-top: 25px; }
    .pa-hero-chips span { display: inline-flex; align-items: center; gap: 7px; border-radius: 9px; padding: 9px 11px; background: rgba(5,30,42,.28); font-size: 12px; }
    .pa-hero-score { align-self: center; border: 1px solid rgba(255,255,255,.18); border-radius: 20px; padding: 23px; background: rgba(5,34,46,.25); backdrop-filter: blur(12px); }
    .pa-hero-score > span { color: #aee8de; font-size: 11px; font-weight: 900; letter-spacing: .12em; }
    .pa-hero-score strong { display: block; margin: 8px 0 7px; font-size: 39px; line-height: 1; letter-spacing: -.045em; }
    .pa-hero-score p { min-height: 40px; margin: 0 0 18px; color: rgba(236,255,252,.76); font-size: 12px; line-height: 1.6; }
    .pa-hero-score small { display: flex; align-items: center; gap: 7px; border-top: 1px solid rgba(255,255,255,.12); padding-top: 14px; color: rgba(255,255,255,.76); font-size: 11px; }
    .pa-hero-score small i { width: 7px; height: 7px; border-radius: 50%; background: #58e0af; box-shadow: 0 0 0 5px rgba(88,224,175,.12); }
    .pa-section-nav { position: relative; z-index: 2; display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); width: calc(100% - 64px); margin: -21px auto 22px; border: 1px solid var(--pa-border); border-radius: 15px; padding: 6px; background: rgba(255,255,255,.96); box-shadow: 0 14px 35px rgba(21,52,68,.11); }
    .pa-section-nav a { display: flex; align-items: center; justify-content: center; gap: 7px; min-height: 46px; border-radius: 10px; color: #5f7481; font-size: 12px; font-weight: 800; text-decoration: none; transition: .2s ease; }
    .pa-section-nav a:hover,.pa-section-nav a.is-active { color: #087f79; background: #e9f7f4; }
    .pa-filter-card,.pa-panel,.pa-method { border: 1px solid var(--pa-border); border-radius: 18px; background: #fff; box-shadow: 0 9px 30px rgba(20,52,68,.06); }
    .pa-filter-card { overflow: hidden; margin-bottom: 18px; }
    .pa-filter-heading,.pa-panel-heading { display: flex; align-items: center; justify-content: space-between; gap: 18px; padding: 18px 21px; }
    .pa-filter-heading > div:first-child,.pa-panel-heading > div:first-child { display: flex; align-items: center; gap: 11px; }
    .pa-heading-icon { display: grid; width: 38px; height: 38px; flex: 0 0 38px; place-items: center; border-radius: 11px; color: var(--pa-teal); background: #e5f7f3; font-size: 18px; }
    .pa-heading-icon.is-blue { color: var(--pa-blue); background: #eaf1ff; }.pa-heading-icon.is-teal { color: var(--pa-teal); background: #e5f7f3; }.pa-heading-icon.is-violet { color: var(--pa-violet); background: #f0edff; }.pa-heading-icon.is-orange { color: var(--pa-orange); background: #fff1e2; }
    .pa-filter-heading h2,.pa-panel-heading h2 { margin: 0; color: var(--pa-ink); font-size: 17px; font-weight: 850; }
    .pa-filter-heading p,.pa-panel-heading p { margin: 4px 0 0; color: var(--pa-muted); font-size: 12px; line-height: 1.45; }
    .pa-panel-heading small { display: block; margin-bottom: 3px; color: #84959f; font-size: 11px; font-weight: 900; letter-spacing: .1em; }
    .pa-presets { display: flex; gap: 5px; }
    .pa-presets button,.pa-panel-actions button { border: 1px solid #dbe6e9; border-radius: 8px; padding: 8px 11px; color: #607783; background: #fff; font-size: 11px; font-weight: 800; }
    .pa-presets button:hover,.pa-presets button.is-active { border-color: #9bd7cc; color: #087f79; background: #eefaf7; }
    .pa-filter-grid { display: grid; grid-template-columns: 1.15fr repeat(2,.8fr) 1.3fr .9fr .75fr .75fr auto; gap: 11px; border-top: 1px solid #edf2f3; padding: 17px 21px 20px; background: #fbfcfc; }
    .pa-field { display: flex; min-width: 0; flex-direction: column; gap: 6px; margin: 0; }
    .pa-field > span { color: #526b79; font-size: 11px; font-weight: 850; letter-spacing: .04em; text-transform: uppercase; }
    .pa-field .form-control,.pa-field .form-select { min-height: 40px; border-color: #dbe5e8; border-radius: 9px; color: #314b5c; background-color: #fff; font-size: 12px; }
    .pa-field-search > div { position: relative; }.pa-field-search i { position: absolute; z-index: 1; left: 10px; top: 9px; color: #8ca0ab; }.pa-field-search input { padding-left: 30px; }
    .pa-filter-actions { display: flex; align-items: end; gap: 6px; }
    .pa-filter-actions .btn { min-height: 40px; white-space: nowrap; border-radius: 9px; padding: 8px 13px; font-size: 12px; font-weight: 850; }
    .pa-btn-primary { color: #fff; background: linear-gradient(135deg,#0a8e80,#0aa26f); }.pa-btn-secondary { border: 1px solid #dbe5e8; color: #607783; background: #fff; }
    .pa-state { display: flex; align-items: center; gap: 12px; margin: 16px 0; border-radius: 13px; padding: 14px 18px; }
    .pa-state b,.pa-state small { display: block; }.pa-state b { font-size: 13px; }.pa-state small { margin-top: 3px; font-size: 11px; }
    .pa-loading { color: #356d72; background: #eaf7f5; }.pa-loading > span { width: 21px; height: 21px; border: 3px solid #b9ded9; border-top-color: #0b9383; border-radius: 50%; animation: pa-spin .75s linear infinite; }
    .pa-error { color: #a43f4e; background: #fff0f2; }.pa-error > i { font-size: 24px; }.pa-error button { margin-left: auto; border: 0; border-radius: 8px; padding: 8px 12px; color: #fff; background: #ca5362; font-size: 11px; font-weight: 800; }
    @keyframes pa-spin { to { transform: rotate(360deg); } }
    .pa-kpi-grid { display: grid; grid-template-columns: repeat(6,minmax(0,1fr)); gap: 12px; margin: 18px 0; }
    .pa-kpi { position: relative; overflow: hidden; min-height: 174px; border: 1px solid var(--pa-border); border-radius: 17px; padding: 18px; background: #fff; box-shadow: 0 8px 25px rgba(20,52,68,.055); }
    .pa-kpi::after { content: ""; position: absolute; width: 76px; height: 76px; right: -32px; top: -31px; border-radius: 50%; background: currentColor; opacity: .055; }
    .pa-kpi > span { display: grid; width: 31px; height: 31px; place-items: center; border-radius: 9px; color: currentColor; background: color-mix(in srgb,currentColor 10%,white); font-size: 15px; }
    .pa-kpi small { display: block; margin-top: 13px; color: #657b88; font-size: 11px; font-weight: 900; letter-spacing: .055em; text-transform: uppercase; }
    .pa-kpi strong { display: block; overflow: hidden; margin: 5px 0; color: var(--pa-ink); font-size: clamp(15px,1.55vw,21px); line-height: 1.1; letter-spacing: -.035em; text-overflow: ellipsis; white-space: nowrap; }
    .pa-kpi p { margin: 0; color: #7d8e98; font-size: 11px; line-height: 1.5; }.pa-kpi.is-navy { color: var(--pa-navy); }.pa-kpi.is-blue { color: var(--pa-blue); }.pa-kpi.is-green { color: var(--pa-green); }.pa-kpi.is-teal { color: var(--pa-teal); }.pa-kpi.is-violet { color: var(--pa-violet); }.pa-kpi.is-orange { color: var(--pa-orange); }
    .pa-panel { overflow: hidden; margin-top: 18px; scroll-margin-top: 85px; }
    .pa-panel-heading { border-bottom: 1px solid #edf2f3; }.pa-panel-actions { display: flex; align-items: center; gap: 8px; }.pa-panel-actions span { color: #6d838f; font-size: 11px; }.pa-panel-actions button { color: #087f79; }
    .pa-table-wrap { overflow-x: auto; }.pa-table { min-width: 1220px; margin: 0; font-size: 12px; }.pa-table thead th { border-bottom: 1px solid #dfe8eb; padding: 13px 14px; color: #586f7d; background: #f7f9fa; font-size: 11px; letter-spacing: .04em; text-transform: uppercase; white-space: nowrap; }.pa-table tbody td { border-color: #edf2f3; padding: 13px 14px; vertical-align: middle; color: #415b6a; }
    .pa-product { display: flex; align-items: center; gap: 9px; min-width: 220px; }.pa-product > span:first-child { display: grid; width: 35px; height: 35px; flex: 0 0 35px; place-items: center; border-radius: 9px; color: var(--pa-teal); background: #e8f7f4; font-size: 16px; }.pa-product b,.pa-product small { display: block; }.pa-product b { max-width: 260px; overflow: hidden; color: #203b4c; font-size: 12px; text-overflow: ellipsis; white-space: nowrap; }.pa-product small { margin-top: 3px; color: #7f929d; font-size: 11px; }
    .pa-rank { display: inline-grid; min-width: 30px; height: 30px; place-items: center; border-radius: 8px; color: #536b79; background: #eef3f4; font-size: 11px; font-weight: 900; }.pa-rank.is-top { color: #a65e16; background: #fff0d8; }
    .pa-number { font-variant-numeric: tabular-nums; white-space: nowrap; }.pa-positive { color: #0b916f; font-weight: 800; }.pa-negative { color: #cf5263; font-weight: 800; }.pa-neutral { color: #778b97; }.pa-metric-pill { display: inline-flex; align-items: center; justify-content: center; min-width: 66px; border-radius: 999px; padding: 6px 9px; color: #087f79; background: #e7f7f3; font-size: 11px; font-weight: 850; }.pa-metric-pill.is-negative { color: #c34657; background: #feecee; }.pa-metric-pill.is-na { color: #7d8e98; background: #eef2f3; }
    .pa-empty { padding: 32px !important; color: #7e909b !important; text-align: center; font-size: 12px; }.pa-table-note { display: flex; align-items: center; gap: 7px; border-top: 1px solid #edf2f3; padding: 13px 18px; color: #708692; background: #fbfcfc; font-size: 11px; line-height: 1.5; }
    .pa-insight-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 18px; }.pa-insight-grid .pa-panel { min-width: 0; }
    .pa-ranking-list { padding: 8px 18px 17px; }.pa-ranking-row { display: grid; grid-template-columns: 31px minmax(0,1fr) auto; align-items: center; gap: 11px; padding: 12px 0; border-bottom: 1px solid #edf2f3; }.pa-ranking-row:last-child { border-bottom: 0; }.pa-ranking-row > b { display: grid; width: 29px; height: 29px; place-items: center; border-radius: 7px; color: #5f7380; background: #eff3f4; font-size: 11px; }.pa-ranking-copy { min-width: 0; }.pa-ranking-copy > div { display: flex; align-items: center; justify-content: space-between; gap: 8px; }.pa-ranking-copy strong { overflow: hidden; color: #284250; font-size: 12px; text-overflow: ellipsis; white-space: nowrap; }.pa-ranking-copy small { color: #657d8a; font-size: 11px; font-weight: 800; white-space: nowrap; }.pa-bar { height: 6px; margin-top: 8px; overflow: hidden; border-radius: 999px; background: #edf2f3; }.pa-bar span { display: block; height: 100%; border-radius: inherit; background: linear-gradient(90deg,#13a58f,#68d3ba); }.pa-ranking-row.is-violet .pa-bar span { background: linear-gradient(90deg,#725bd0,#ad9bf0); }.pa-ranking-note { color: #7e929e; font-size: 11px; text-align: right; }
    .pa-top-badge { display: inline-flex; align-items: center; gap: 5px; border-radius: 999px; padding: 7px 10px; color: #b2681f; background: #fff1df; font-size: 11px; font-weight: 850; }
    .pa-top-grid { display: grid; grid-template-columns: repeat(5,minmax(0,1fr)); gap: 11px; padding: 17px; }.pa-top-card { position: relative; min-width: 0; border: 1px solid #e6ecee; border-radius: 14px; padding: 16px; background: linear-gradient(180deg,#fff,#fbfcfc); }.pa-top-card > span { position: absolute; right: 11px; top: 10px; color: #d58a38; font-size: 23px; font-weight: 900; opacity: .16; }.pa-top-card i { color: #d88731; font-size: 18px; }.pa-top-card h3 { overflow: hidden; margin: 11px 0 4px; color: #273f4e; font-size: 12px; font-weight: 850; text-overflow: ellipsis; white-space: nowrap; }.pa-top-card small { display: block; color: #7d909b; font-size: 11px; }.pa-top-card strong { display: block; margin-top: 13px; color: #07866c; font-size: 15px; }.pa-top-card p { margin: 5px 0 0; color: #6f838f; font-size: 11px; line-height: 1.45; }
    .pa-method { display: flex; align-items: center; justify-content: space-between; gap: 20px; margin-top: 18px; padding: 17px 19px; background: #f8fbfb; }.pa-method > div { display: flex; align-items: center; gap: 11px; }.pa-method i { color: var(--pa-teal); font-size: 24px; }.pa-method b,.pa-method small { display: block; }.pa-method b { color: #31505e; font-size: 12px; }.pa-method small,.pa-method p { color: #708692; font-size: 11px; line-height: 1.6; }.pa-method p { max-width: 440px; margin: 0; text-align: right; }
    .pa-toast { position: fixed; z-index: 1080; right: 22px; bottom: 22px; max-width: 360px; transform: translateY(18px); border-radius: 11px; padding: 12px 15px; color: #fff; background: #173b4b; box-shadow: 0 14px 35px rgba(0,0,0,.18); font-size: 12px; opacity: 0; pointer-events: none; transition: .2s ease; }.pa-toast.is-visible { transform: none; opacity: 1; }
    @media (max-width: 1350px) { .pa-filter-grid { grid-template-columns: repeat(4,minmax(0,1fr)); }.pa-filter-actions { justify-content: flex-end; }.pa-kpi-grid { grid-template-columns: repeat(3,minmax(0,1fr)); }.pa-top-grid { grid-template-columns: repeat(3,minmax(0,1fr)); } }
    @media (max-width: 850px) { .pa-hero { grid-template-columns: 1fr; padding: 29px 24px; }.pa-section-nav { width: calc(100% - 24px); grid-template-columns: repeat(2,1fr); }.pa-filter-heading,.pa-panel-heading,.pa-method { align-items: flex-start; flex-direction: column; }.pa-filter-grid { grid-template-columns: repeat(2,minmax(0,1fr)); }.pa-insight-grid { grid-template-columns: 1fr; }.pa-top-grid { grid-template-columns: repeat(2,minmax(0,1fr)); }.pa-method p { max-width: none; text-align: left; } }
    @media (max-width: 540px) { .pa-hero { border-radius: 18px; }.pa-hero h1 { font-size: 32px; }.pa-section-nav { grid-template-columns: 1fr; }.pa-filter-grid,.pa-kpi-grid,.pa-top-grid { grid-template-columns: 1fr; }.pa-presets { width: 100%; overflow-x: auto; }.pa-filter-actions .btn { flex: 1; }.pa-filter-actions { width: 100%; }.pa-kpi { min-height: 135px; } }
</style>
